# =============================================================================
# Goast GitHub Labels Configuration
# =============================================================================
#
# This file defines the label taxonomy for programmatic management.
# Use with github-label-sync or similar tools:
#   npx github-label-sync --labels .github/labels.yml plannededge/goast
#
# Label Format: category:value (lowercase, hyphenated)
# =============================================================================

# -----------------------------------------------------------------------------
# TYPE: What kind of work is this?
# Color: Blue (#0052CC)
# -----------------------------------------------------------------------------
- name: "type:bug"
  color: "0052CC"
  description: "Something isn't working correctly"

- name: "type:feature"
  color: "0052CC"
  description: "New functionality or capability"

- name: "type:enhancement"
  color: "0052CC"
  description: "Improvement to existing feature"

- name: "type:docs"
  color: "0052CC"
  description: "Documentation updates"

- name: "type:chore"
  color: "0052CC"
  description: "Maintenance, dependencies, cleanup"

- name: "type:security"
  color: "0052CC"
  description: "Security-related issues"

- name: "type:research"
  color: "0052CC"
  description: "Investigation or technical spike"

# -----------------------------------------------------------------------------
# PRIORITY: How urgent is this?
# Color: Red to Orange gradient (#B60205 → #FBCA04)
# -----------------------------------------------------------------------------
- name: "priority:critical"
  color: "B60205"
  description: "Drop everything, fix now"

- name: "priority:high"
  color: "D93F0B"
  description: "Address in current sprint"

- name: "priority:medium"
  color: "FBCA04"
  description: "Normal priority"

- name: "priority:low"
  color: "FEF2C0"
  description: "Nice to have, backlog"

# -----------------------------------------------------------------------------
# STATUS: What is the current state?
# Color: Purple (#7B68EE)
# -----------------------------------------------------------------------------
- name: "status:triage"
  color: "7B68EE"
  description: "Needs review and categorization"

- name: "status:blocked"
  color: "7B68EE"
  description: "Cannot proceed, waiting on dependency"

- name: "status:in-progress"
  color: "7B68EE"
  description: "Actively being worked on"

- name: "status:review"
  color: "7B68EE"
  description: "Ready for code review"

- name: "status:ready"
  color: "7B68EE"
  description: "Refined and ready to implement"

# -----------------------------------------------------------------------------
# AREA: Which part of the system?
# Color: Green (#00875A)
# -----------------------------------------------------------------------------
- name: "area:frontend"
  color: "00875A"
  description: "UI/UX, client-side code"

- name: "area:backend"
  color: "00875A"
  description: "API, server-side logic"

- name: "area:ai"
  color: "00875A"
  description: "AI/ML, The Polisher, Vibe Check"

- name: "area:infra"
  color: "00875A"
  description: "DevOps, CI/CD, infrastructure"

- name: "area:mobile"
  color: "00875A"
  description: "Mobile-specific (PWA/native)"

- name: "area:database"
  color: "00875A"
  description: "Database, Prisma, migrations"

- name: "area:realtime"
  color: "00875A"
  description: "WebSocket, real-time features"

# -----------------------------------------------------------------------------
# EFFORT: How big is this task?
# Color: Teal (#00B8D9)
# -----------------------------------------------------------------------------
- name: "effort:xs"
  color: "00B8D9"
  description: "Extra small (< 1 hour)"

- name: "effort:s"
  color: "00B8D9"
  description: "Small (1-4 hours)"

- name: "effort:m"
  color: "00B8D9"
  description: "Medium (1-2 days)"

- name: "effort:l"
  color: "00B8D9"
  description: "Large (3-5 days)"

- name: "effort:xl"
  color: "00B8D9"
  description: "Extra large (> 1 week)"

# -----------------------------------------------------------------------------
# BUG: Bug severity classification
# Color: Red (#D73A4A)
# -----------------------------------------------------------------------------
- name: "bug:critical"
  color: "D73A4A"
  description: "System down, data loss risk"

- name: "bug:major"
  color: "D73A4A"
  description: "Core feature broken"

- name: "bug:minor"
  color: "D73A4A"
  description: "Non-critical malfunction"

- name: "bug:cosmetic"
  color: "D73A4A"
  description: "Visual/UI defect only"

- name: "bug:regression"
  color: "D73A4A"
  description: "Previously working, now broken"

# -----------------------------------------------------------------------------
# FEATURE: Feature category (Goast-specific)
# Color: Cyan (#1D76DB)
# -----------------------------------------------------------------------------
- name: "feature:core"
  color: "1D76DB"
  description: "Core chat/messaging mechanics"

- name: "feature:governance"
  color: "1D76DB"
  description: "Voting, democracy features"

- name: "feature:identity"
  color: "1D76DB"
  description: "Avatars, usernames, badges"

- name: "feature:economy"
  color: "1D76DB"
  description: "Token system, costs"

- name: "feature:dissolution"
  color: "1D76DB"
  description: "Goast lifecycle, fading"

- name: "feature:ai-polish"
  color: "1D76DB"
  description: "Message polishing AI"

# -----------------------------------------------------------------------------
# RELEASE: Target release phase
# Color: Gold (#FEF2C0)
# -----------------------------------------------------------------------------
- name: "release:alpha"
  color: "FEF2C0"
  description: "Phase 1: Closed Alpha (Q1 2026)"

- name: "release:beta"
  color: "FEF2C0"
  description: "Phase 2: Invite-Only Beta (Q2 2026)"

- name: "release:v1"
  color: "FEF2C0"
  description: "Phase 3: Public Launch (Q3 2026)"

# -----------------------------------------------------------------------------
# STANDALONE: Common labels without category prefix
# -----------------------------------------------------------------------------
- name: "good-first-issue"
  color: "7057FF"
  description: "Good for newcomers"

- name: "help-wanted"
  color: "008672"
  description: "Extra attention needed"

- name: "wontfix"
  color: "FFFFFF"
  description: "Will not be addressed"

- name: "duplicate"
  color: "CFD3D7"
  description: "Duplicate of another issue"

- name: "invalid"
  color: "E4E669"
  description: "Not valid/applicable"
