name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type:feature", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please fill out what you can. If you are unsure about a field, leave it blank.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: It is hard to stop notifications late at night.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: Add a quiet hours setting so notifications pause between chosen times.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you tried any workarounds?
      placeholder: I use phone-wide do not disturb, but that mutes everything.
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of Goast does this relate to?
      options:
        - "Core - Chat/messaging mechanics"
        - "Governance - Voting/democracy features"
        - "Identity - Avatars/usernames/badges"
        - "Economy - Token system"
        - "Dissolution - Goast lifecycle/fading"
        - "AI Polish - Message polishing"
        - "Other"
    validations:
      required: false

  - type: dropdown
    id: target
    attributes:
      label: Target Release
      description: When would this ideally be available?
      options:
        - "Alpha - Q1 2026"
        - "Beta - Q2 2026"
        - "V1 Launch - Q3 2026"
        - "Post-launch / Future"
        - "Not sure"
    validations:
      required: false

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: Rough size estimate, if you have one.
      options:
        - "XS - Quick win (< 1 hour)"
        - "S - Small (1-4 hours)"
        - "M - Medium (1-2 days)"
        - "L - Large (3-5 days)"
        - "XL - Extra large (> 1 week)"
        - "Not sure"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any extra details, mockups, or examples.
      placeholder: Sketches, links, or a short example would be helpful.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
          required: false
