name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type:feature", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We love hearing ideas from the community.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've thought about...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of Goast does this relate to?
      options:
        - "Core - Chat/messaging mechanics"
        - "Governance - Voting/democracy features"
        - "Identity - Avatars/usernames/badges"
        - "Economy - Token system"
        - "Dissolution - Goast lifecycle/fading"
        - "AI Polish - Message polishing"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: target
    attributes:
      label: Target Release
      description: When would this ideally be available?
      options:
        - "Alpha - Q1 2026"
        - "Beta - Q2 2026"
        - "V1 Launch - Q3 2026"
        - "Post-launch / Future"
        - "Not sure"
    validations:
      required: false

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How big do you think this feature is?
      options:
        - "XS - Quick win (< 1 hour)"
        - "S - Small (1-4 hours)"
        - "M - Medium (1-2 days)"
        - "L - Large (3-5 days)"
        - "XL - Extra large (> 1 week)"
        - "Not sure"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
      placeholder: Add any additional context here...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
          required: false
